### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by barrycarton** [Sekund/sekund-plugin-react#1]
Hey Candide 
Great concept. Unfortunately I am unable to install your plugin.
Maybe you should update the instructions.
This is what I see when I open the community plugins tab in the Settings modal.
![Screenshot 2021-11-03 at 10 16 09](https://user-images.githubusercontent.com/201714/140034980-82c637e5-5e91-4121-90de-9061214271c3.png)

**Comment by ckemmler** [comment]
You need to turn Safe Mode off. You will then be able to see all Community plugins + those that you have installed manually.

Please download the [latest archive](https://sekund.s3.amazonaws.com/sekund-obsidian-plugin.zip) again, as I just uploaded a new release with lots of bug fixes.

**Comment by ckemmler** [comment]
considering this closed
