### ISSUE TITLE
feature request: allows users to specify the location and name of the Sekund folder

### ISSUE THREAD

**Issue by eleanorkonik** [Sekund/sekund-plugin-react#11]
I use a pretty strict Johnny Decimal folder structure and would strongly prefer if I could put the Sekund folder in my "automations" folder for organizational purposes. I imagine other users would also like to be able to determine where their Sekund notes are. This has precedent: daily notes, templater, the SRS plugins, etc. all permit this.

**Comment by ckemmler** [comment]
That makes perfect sense. Thanks Eleanor.

**Comment by kenjibailly** [comment]
Was looking for this as well!

**Comment by ckemmler** [comment]
OK, so I created a [branch](https://github.com/Sekund/sekund-plugin-react/tree/custom-sekund-folder) to work on that.

I am currently having a problem for when the user has chosen a custom folder and Obsidian now has to move the files from the previous Sekund folder (e.g. `__sekund__`) to the new one. Specifically it looks like `vault.rename` is picky about folders it allows to rename.

Here's a [comment pointing to the code in question](https://github.com/Sekund/sekund-plugin-react/commit/0607966f94fefdbbd0ee01d35cebff92e6a6fca4#r68097888).
