### ISSUE TITLE
Don't use illegal characters for file names

### ISSUE THREAD

**Issue by kometenstaub** [Sekund/sekund-plugin-react#16]
The plugin created a `**README**.md` file. When syncing it to Android, it cannot create that file. I worked around it by excluding the folder from Sync. 

Per @lishid, these are the illegal chars for Obsidian Android:

`|\\?*<\":>+[]/'`

**Comment by lishid** [comment]
Actually these characters are not allowed on Android's file system itself.

**Comment by ckemmler** [comment]
fixed in 1.0.50
