### ISSUE TITLE
Security and privacy of plugin

### ISSUE THREAD

**Issue by HEmile** [Sekund/sekund-plugin-react#2]
Hi,

This looks like it could be a very useful plugin that many in the community have been asking for. However, I see very little in the README about the security and privacy terms of this plugin. Can you make this more clear? What happens to notes that are shared in Sekund? Is it E2E encrypted (the site suggest it isn't!)?

**Comment by ckemmler** [comment]
The website says it clearly: "Support for [end-2-end encryption](https://en.wikipedia.org/wiki/End-to-end_encryption) will be added in the near future." 

Thus, at this point, E2E encryption is NOT supported. The plan is to implement it as soon as enough people are using the plugin and asking for this feature.

Currently, notes that are shared in Sekund are stored in a cloud-based backend. Specifically, Sekund uses MongoDB Realm for user management, authentication and authorization. Shared notes will obviously only be visible to users with whom they have been shared. However, this being, so far, a one-man effort, there is indeed no legal framework around those issues. This project stems primarily from a desire to support the Obsidian Community on a "best effort" basis.

Obviously, E2E encryption would clear things up and yes, some Terms of Services are probably needed.

Any help on this is heartily welcome.
