### ISSUE TITLE
Cannot confirm my account

### ISSUE THREAD

**Issue by Andrea-28-03** [Sekund/sekund-plugin-react#21]
I'm just registred into the obsidian plug in and it show that it had sent the confirmation email:
![image](https://user-images.githubusercontent.com/62112468/165263893-e4e3e633-5ea4-40b5-a803-590044bf7ac5.png)

The confirmation email is arrived but when i try to open the link this error appear:
![image](https://user-images.githubusercontent.com/62112468/165263757-b8e4d476-ef0d-443a-b289-4c74a967edb9.png)

**Comment by ckemmler** [comment]
Hi Andrea,
Thank you for reporting. This issue is now fixed.
If you get a chance, please tell me what you think.
BR,
Candide


------- Original Message -------

**Comment by ckemmler** [comment]
I also fixed the dummy labels in the UI: you will get the english (default) labels, until someone volunteers to translate them to italian ;-)
