### ISSUE TITLE
Version for mobile

### ISSUE THREAD

**Issue by mnaoumov** [Sekund/sekund-plugin-react#22]
Is there any specific reason this plugin was made for desktop only?

**Comment by ckemmler** [comment]
No, it's just that it doesn't work on mobile and I haven't yet figured out how to investigate that.

**Comment by mnaoumov** [comment]
@ckemmler it's relatively simple to do on Android devices

https://developer.chrome.com/docs/devtools/remote-debugging/

As Obsidian is an Electron app, you can debug it from your computer using `chrome://inspect` endpoint

**Comment by ckemmler** [comment]
I don't have an android device. I tried KjellConnely's plugin ([obsidian-dev-tools](https://github.com/KjellConnelly/obsidian-dev-tools)) but it only lets you toggle the console when the vault has loaded, and that's too late to catch errors about a plugin that's not loading.

I'll keep tracking ways to debug on iOS, but until then, there's not much I can do.

**Comment by mnaoumov** [comment]
@ckemmler I haven't tried it, but it seems there is a similar technique for iOS: https://ionicframework.com/docs/troubleshooting/debugging

**Comment by ckemmler** [comment]
Yes I know about that, but for some reason, Obsidian isn't getting listed:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/41804/166256176-7f7cc724-d81c-4e6b-8e8a-7e1e1ef613f2.png">

**Comment by ckemmler** [comment]
I was finally able to debug this using an android device. The fault was on the mime-types module, which is meant for use in Node.js, not in a browser, and uses `path`. Now using `ext-name` instead
