### ISSUE TITLE
Enhancement: Remember the position of the divider that separates the Sekund sidepanel

### ISSUE THREAD

**Issue by MSBack** [Sekund/sekund-plugin-react#23]
As it is, the draggable divider between the two sections of the Sekund sidepanel keeps resetting in a position where the list of uploaded/sharable notes is not visible. I keep having to drag the divider into a desired position. If the position could somehow be fixed or remembered, then this wouldn't be a bother.

**Comment by ckemmler** [comment]
Should be fixed now, position is saved in the plugin's settings
