### ISSUE TITLE
Public note links do not load: Internal server error 500

### ISSUE THREAD

**Issue by MSBack** [Sekund/sekund-plugin-react#25]
After creating public note links, and trying to open them, I am met with an internal server error 500. I tried three different notes, but none worked. One of the links was the following: [https://public.sekund.org/629f6d061a27ff3deec87d15/biogass/](https://public.sekund.org/629f6d061a27ff3deec87d15/biogass/)

**Comment by ckemmler** [comment]
Þakka þér fyrir
It should work better now

**Comment by MSBack** [comment]
Not Icelandic, but close ;) Thanks, it works now!
