### ISSUE TITLE
Inclusions feature is not working

### ISSUE THREAD

**Issue by Another5405** [Sekund/sekund-plugin-react#26]
<img width="115" alt="CleanShot 2022-06-22 at 22 37 36@2x" src="https://user-images.githubusercontent.com/67992869/175056772-ac45a896-7053-4d7b-b979-db2121545204.png">

I try sekund today, I sign up two account and upload one note"456" from account A for test,
but account B did't have the linked note 123.

According on other issues report,this issue on my own maybe,
Apologies in advance if I misunderstood this feature.

Also,is Inclusions support dataview or inlinks?

**Comment by ckemmler** [comment]
By inclusion I mean "embedded notes" using the `![[...` markdown syntax
